version: '3.8'
services:
  blackfury:
    image: blackfuryzone/blackfury:latest
    hostname: blackfury
    volumes:
      - ./data/qstest-1:/blackfury/.blackfuryd
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 26657:26657
      - 1317:1317
  blackfury2:
    image: blackfuryzone/blackfury:latest
    hostname: blackfury2
    volumes:
      - ./data/qstest-1a:/blackfury/.blackfuryd
    build:
      context: .
      dockerfile: Dockerfile
  blackfury3:
    image: blackfuryzone/blackfury:latest
    hostname: blackfury3
    volumes:
      - ./data/qstest-1b:/blackfury/.blackfuryd
    build:
      context: .
      dockerfile: Dockerfile
  testzone1-1:
    image: blackfuryzone/testzone:latest
    hostname: testzone1-1
    volumes:
      - ./data/lstest-1:/icad/.ica
    command:
      - icad
      - start
    ports:
    - 27657:26657
    - 23137:1317
  testzone1-2:
    image: blackfuryzone/testzone:latest
    hostname: testzone1-2
    volumes:
      - ./data/lstest-1a:/icad/.ica
    command:
      - icad
      - start
  testzone1-3:
    image: blackfuryzone/testzone:latest
    hostname: testzone1-3
    volumes:
      - ./data/lstest-1b:/icad/.ica
    command:
      - icad
      - start
  testzone1-4:
    image: blackfuryzone/testzone:latest
    hostname: testzone1-4
    volumes:
      - ./data/lstest-1c:/icad/.ica
    command:
      - icad
      - start
  testzone2-1:
    image: blackfuryzone/qsosmosis:v12.1.0
    hostname: testzone2-1
    build:
      context: .
      dockerfile: Dockerfile.osmosis
    volumes:
      - ./data/lstest-2:/osmosis/.osmosisd
    command:
      - osmosisd
      - start
  testzone2-2:
    image: blackfuryzone/qsosmosis:v12.1.0
    hostname: testzone2-2
    volumes:
      - ./data/lstest-2a:/osmosis/.osmosisd
    command:
      - osmosisd
      - start
  testzone2-3:
    image: blackfuryzone/qsosmosis:v12.1.0
    hostname: testzone2-3
    volumes:
      - ./data/lstest-2b:/osmosis/.osmosisd
    command:
      - osmosisd
      - start
  testzone2-4:
    image: blackfuryzone/qsosmosis:v12.1.0
    hostname: testzone2-4
    volumes:
      - ./data/lstest-2c:/osmosis/.osmosisd
    command:
      - osmosisd
      - start
  hermes:
    image: blackfuryzone/hermes:v1.5.0
    hostname: hermes
    volumes:
      - ./data/hermes:/hermes/.hermes
    command:
      - hermes
      - start
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.hermes
  icq:
    image: blackfuryzone/interchain-queries:v0.9.1
    volumes:
      - ./data/icq:/icq/.icq
    command:
      - interchain-queries
      - run
    restart: always
  icq2:
    image: blackfuryzone/interchain-queries:v0.9.1
    volumes:
      - ./data/icq2:/icq/.icq
    command:
      - interchain-queries
      - run
    restart: always
  relayer:
    image: blackfuryzone/relayer:v2.3.0
    build:
      context: .
      dockerfile: Dockerfile.relayer
    volumes:
      - ./data/rly:/rly/.relayer
    command:
      - rly
      - start
      - demo
      #- -p
      #- events
      #- -b
      #- "100"
    restart: always
